[package]
name = "micropb-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["format"]
format = ["dep:prettyplease"]

[dependencies]
prost-types = "0.12"
prost = { version = "0.12", default-features = false, features = ["std"] }
quote = "1"
proc-macro2 = "1"
syn = { version = "2", default-features = false, features = ["parsing", "derive", "printing"] }
convert_case = "0.6"
prettyplease = { version = "0.2.17", optional = true }

[dev-dependencies]
syn = { version = "2", default-features = false, features = ["extra-traits"] }
